language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install: composer install
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search